name: Get latest release and publish to npm

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-latest-inklecate-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'inkle/ink'
          latest: true
          fileName: '*'
        id: get-release
      
      - name: Unzip binaries
        run: |
          mkdir -p ./bin
          unzip inklecate_linux.zip -d ./bin/linux
          unzip inklecate_mac.zip -d ./bin/mac
          unzip inklecate_windows.zip -d ./bin/windows
          rm inklecate_*.zip

      - name: Write version from release tag to package.json
        run: |
          VERSION="${{steps.get-release.outputs.tag_name}}-alpha"
          VERSION="${VERSION#v}"
          VERSION="${VERSION#.}"
          jq --arg VERSION "$VERSION" '.version = $VERSION' package.json > package_with_version.json
          mv package_with_version.json package.json
          
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --access public
