name: Get latest release and publish to npm

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-latest-inklecate-release:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repo so we can commit back to it later
      - uses: actions/checkout@v4

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'inkle/ink'
          latest: true
          fileName: '*'
      
      - name: Unzip binaries
        run: |
          mkdir -p ./bin
          unzip inklecate_linux.zip -d ./bin/linux
          unzip inklecate_mac.zip -d ./bin/mac
          unzip inklecate_windows.zip -d ./bin/windows
