name: Get latest release and publish to npm

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-latest-inklecate-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      committed: ${{steps.commit.outputs.committed}}

    steps:
      - uses: actions/checkout@v4

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'inkle/ink'
          latest: true
          fileName: '*'
        id: get-release
      
      - name: Unzip binaries
        run: |
          mkdir -p ./bin
          unzip inklecate_linux.zip -d ./bin/linux
          unzip inklecate_mac.zip -d ./bin/mac
          unzip inklecate_windows.zip -d ./bin/windows
          rm inklecate_*.zip

      - name: Write version from release tag to package.json
        run: |
          VERSION="${{steps.get-release.outputs.tag_name}}-alpha2"
          VERSION="${VERSION#v}"
          VERSION="${VERSION#.}"
          jq --arg VERSION "$VERSION" '.version = $VERSION' package.json > package_with_version.json
          mv package_with_version.json package.json

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: |
            - bin
            - package.json
        id: commit

  publish-to-npm:
    needs: get-latest-inklecate-release
    if: ${{jobs.get-latest-inklecate-release.outputs.committed}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: latest
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm publish --access public --tag alpha
